insert into softskills (keyword)
values 
('Leadership'),
('Active listening'),
('Clarity'),
('Collaboration'),
('Confidence'),
('Counseling'),
('Cross-cultural communication'),
('Diplomacy'),
('Empathy'),
('Feedback'),
('Friendliness'),
('Leadership'),
('Mediation'),
('Negotiation'),
('Nonverbal communication'),
('Open-mindedness'),
('Phone calls'),
('Presentation'),
('Problem sensitivity'),
('Public speaking'),
('Summarizing'),
('Teaching'),
('Verbal communication'),
('Written communication'),
('Creative thinking'),
('Critical thinking'),
('Decision making'),
('Interpersonal skills'),
('Language skills'),
('Leadership'),
('Management'),
('Mediation'),
('Motivation'),
('Negotiating'),
('Problem-solving'),
('Relationship building'),
('Reliable'),
('Team management'),
('Team oriented'),
('Team player'),
('Interpersonal Skills'),
('Good Attitude '),
('Decision-making skills'),
('Interpersonal skills'),
('Teamwork skills'),
('Organizational skills'),
('Writing skills'),
('Communication'),
('Time management'),
('Attention to detail'),
('Office coordination'),
('Videoconferencing'),
('Problem solving'),
('Event coordination'),
('Calendar management'),
('Email management'),
('Self confidence '),
('honesty'),
('customer service'),
('dependability'),
('compassion'),
('judgement'),
('ethical'),
('Verbal communication'),
('Body Language'),
('Physical Communication'),
('Writing'),
('Storytelling'),
('Visual Communication'),
('Humor'),
('Quick-wittedness'),
('Listening'),
('Presentation Skills'),
('Public Speaking'),
('Interviewing'),
('eam Building'),
('Strategic Planning'),
('Coaching'),
('Mentoring'),
('Delegation'),
('Dispute Resolution'),
('Diplomacy'),
('Giving Feedback'),
('Managing Difficult Conversations'),
('Decision Making'),
('Performance Management'),
('Supervising'),
('Managing'),
('Manager Management'),
('Talent Management'),
('Managing Remote Teams'),
('Managing Virtual Teams'),
('Crisis Management'),
('Facilitation'),
('Selling'),
('Inspiring'),
('Persuasion'),
('Negotiation'),
('Motivating'),
('Collaborating'),
('Networking'),
('Interpersonal Relationships'),
('Dealing with Difficult People'),
('Conflict Resolution'),
('Personal Branding'),
('Office Politics'),
('Emotional Intelligence'),
('Self Awareness'),
('Emotion Management'),
('Stress Management'),
('Tolerance of Change and Uncertainty'),
('Taking Criticism'),
('Self Confidence'),
('Adaptability'),
('Resilience'),
('Assertiveness'),
('Competitiveness'),
('Self Leadership'),
('Self Assessment'),
('Work-Life Balance'),
('Friendliness'),
('Enthusiasm'),
('Empathy'),
('Problem Solving'),
('Critical Thinking'),
('Innovation'),
('Troubleshooting'),
('Design Sense'),
('Artistic Sense'),
('Organization'),
('Planning'),
('Scheduling'),
('Time Management'),
('Meeting Management'),
('Technology Savvy'),
('Technology Trend Awareness'),
('Business Trend Awareness'),
('Research'),
('Business Etiquette'),
('Business Ethics'),
('Diversity Awareness'),
('Disability Awareness'),
('Intercultural Competence'),
('Training'),
('Train the Trainer'),
('Process Improvement'),
('Knowledge Management'),
('Writing Reports and Proposals'),
('Customer Service'),
('Entrepreneurial Thinking')
;
