const editText = function (text){
// console.log( "text here is ", text)
  const clearText = text
    .replace(/[^a-zA-Z0-9 ]/g, " ")
    .toLowerCase()
    .split(" ");
  const inputText = clearText.filter((word) => word !== "");
  // console.log(inputText);
  let wordRank = {};
  for (let word of inputText) {
    if (!wordRank[word]) {
      wordRank[word] = 1;
    } else {
      wordRank[word] += 1;
    }
  }
  const wordExclusions = ["and","the","is","but","a","or","job","as","be","by","for","from","in"," ","  ","","to","of","an","at","on","with","that","uses","are","who","you"];
  const sortable = [];
  for (let word in wordRank) {
    if(!wordExclusions.includes(word))  
    sortable.push([word, wordRank[word]]);
  }
  sortable.sort(function(a, b) {
    return b[1] - a[1];
  });
  let objSorted = {}
  sortable.forEach(function(item){
      objSorted[item[0]]=item[1]
  })
  return objSorted
}
const compareText = function (resume, posting){
const editResume = editText(resume);
const editJob = editText(posting);

// let resumeArray = [];
// for (let item of editResume) {
//   resumeArray.push(item[0].toLowerCase());
// }

// let JobArray = [];
// for (let item of editJob) {
//   JobArray.push(item[0].toLowerCase());
// }

let sortable = []
for (let word in editJob) {
  for (let word2 in editResume){
    if(word === word2)  
    sortable.push([word, editJob[word]]);

  }
}
sortable.sort(function(a, b) {
  return b[1] - a[1];
});

console.log(sortable);
// console.log("resumeArray", resumeArray)
// console.log("job posting", JobArray)
}
const resume = `Work Experience
2011 - Present
Toronto, ONWeb Developer | Web Design Co.
Discuss options with clients to make sure websites meet their needs as well as the needs of their customers
Develop websites for variety of companies while maintaining consistent feel and brand awareness
Provide technical support to high-level users
2008 - 2011
Toronto, ONAssistant Web Developer | SEO Providers Canada
Provided direct assistance to head web developer
Managed websites and design/creation for clients around the country
Performed weekly assessments of all websites and software to look for potential problems or crashes
2011 - 2011
Toronto, ONFreelance Web Designer | Freelance
Wrote external and internal design specs for clients
Maintained and updated customer websites as needed safety
Participated in weekly mentoring sessions with web developers within the organization experience
Education
2007 - 2011
Regina, SKUniversity of Regina
B.S. Web Application Development
Additional Skills & Interest
Strong skills in JavaScript/jQuery, PHP, CSS, XHTML, HTML, and XML
Knowledge of social media strategy and integration with websites
Understanding of international protocols and web standards`;

const job = `Blackline Safety is looking for a Visualization and Frontend Developer to help build and drive our Blackline Analytics and Blackline Vision platform. We have a world class connected safety system and we are building a data, analytics, and data science platform to match it.
Who are you?
You believe big data helps businesses solve real-world problems. You are skilled at data visualization techniques and frameworks. You are not bound to a single tool or platform, and can solve problems in creative ways. You trust in data driven problem solving and believe visualizing large datasets is a necessity to achieve that. You like to explore datasets to find insights that nobody else sees. You can communicate these ideas through visualizations. You are self-motivated, creative and excited to find answers to questions that the answer might not be obvious without going through large amounts of data.
What will you do?
You will be responsible for developing custom visualizations that are designed by our Visualization Designers for our Blackline Analytics, and Blackline Vision platforms. You will be involved in building interactive visualizations that will be used by our marketing, business intelligence, and data science teams as well as our end users. These projects will include both web development, and visualization development in the Power platform – Power BI, Power Flow, Power Apps.
Your job will include everything from collaborating with our designers, building high fidelity proof of concepts, and production ready scalable products. Your contribution will help us increase internal efficiencies and evolve our products and services by leveraging large and diverse datasets generated by customers from around the world.
About Blackline
Blackline Safety is a world leader in the development and manufacturing of wirelessly connected safety products — we offer the broadest and most complete portfolio in the industry. We monitor personnel working alone in populated areas, indoors within complex facilities, and employees operating in the most remote reaches of our planet. Our products are used to keep people safe in the event of falls, missed check-ins, man-downs and exposure to explosive or toxic gas. Our products save lives. Our design, marketing, customer care, sales and production are all performed in-house at our headquarters in Calgary, AB. Blackline Safety is a publicly-traded company (TSXV: BLN). Blackline Safety’s headquarters are located in an historic building in Ramsay. We have a robust COVID protocol, with employees working both in the office and remotely.
Requirements:
Post-secondary degree (Computer Science, Human-Computer Interaction, Information Visualization, Analytics, Computer Graphics, Mathematics, Physics, Information Technology, Computational Media Design, or related)
5 years of visualization development experience (Including academia and personal projects)
3 years of experience with React.js
3 years of experience with D3.js
3 years of experience with Node.js (For building Power BI custom visuals)
Strong communication skills in written, spoken, and visualization mediums.
Experience working with technical and design teams
Comfortable working in an iterative process
Comfort troubleshooting and fixing performance issues related to visualization delivery
Preferred: Previously built and deployed visualizations with a major tool such as PowerBI, Tableau, Qlik or Spotfire
Optional:
Experience with development and deployment of Power BI widgets,
Experience working in research and exploration-oriented teams,
Experience with CSS, Web applications, and HTML would be considered an asset
Experience with DAX and M would be considered an asset,
Experience with SQL and structured database systems would be considered an asset,
Experience with Python would be considered an asset.
Experience with version control.
Blackline Safety offers:
An exciting high-growth environment
An experienced, dynamic and motivated team
Supportive, challenging and collaborative work
Competitive salary and vacation
Medical, dental and drug benefits
Company stock purchase plan with matching contributions
Our clients depend on Blackline Safety to monitor the wellbeing of their employees at work — you can help to make a difference. Come work with Blackline Safety in an exciting, fast-paced work environment.. java React , ruby on rails Strong JS skills, react skills ruby on rails react particularly with es6, React, Vue, Angular, Express, Node Experience with with various PHP frameworks/CMS like Laravel, Drupal, and WordPress Experience with Java and Java based technologies and frameworks (Spring, Hibernate) Experience designing RESTful API Experience with microservices architecture Proficiency with relational databases and NoSQL databases. (MySQL, MongoDB, Couchbase, DynamoDB, PostgreSQL) Knowledge of version control systems and continuous integration systems (Git, Bitbucket, Jenkins, Travis CI). Proven experience in agile/scrum methodologies Experience with CloudComputing and Serverless Architecture. (AWS, GCP, Azure) Solid analytical, problem solving and decision-making skills Excellent written documentation and client-facing presentation skills Understanding of software architectural patterns Unit and automated testing Continuous deployment process and infrastructure management Analytics, data analysis, reporting@`

console.log( compareText(resume, job))
module.exports = {editText}